<?php

namespace Container3RHKcor;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Zn6tQVw.App\Entity\Prestations' shared service.
     *
     * @return \App\Entity\Prestations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Zn6tQVw": it references class "App\\Entity\\Prestations" but no such service exists.');
    }
}
