<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOoMxfjX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOoMxfjX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOoMxfjX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOoMxfjX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOoMxfjX\App_KernelDevDebugContainer([
    'container.build_hash' => 'OoMxfjX',
    'container.build_id' => 'e1c588ea',
    'container.build_time' => 1605193059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOoMxfjX');
