<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3RHKcor\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3RHKcor/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3RHKcor.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3RHKcor\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3RHKcor\App_KernelDevDebugContainer([
    'container.build_hash' => '3RHKcor',
    'container.build_id' => '450f059e',
    'container.build_time' => 1605271770,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3RHKcor');
